### ISSUE TITLE
Story "Upgrade FAAAST"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents-aas-bridge#5]
# Story "Upgrade FAAAST"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to support the AAS 3.0 specification.

## Acceptance Criteria

- FAAAST release that supports AAS 3.0

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/306#issuecomment-1770953080_

**Comment by drcgjung** [comment]
FAAAST 1.0.1 released https://github.com/FraunhoferIOSB/FAAAST-Service/releases/tag/v1.0.1

AAS 3.0.1 + Meta-Model 3.0
