### ISSUE TITLE
Story "Upgrade AAS4J"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents-aas-bridge#6]
# Story "Upgrade AAS4J"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to support the AAS 3.0 specification.

## Acceptance Criteria

- AAS4J that supports AAS 3.0

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/306#issuecomment-1770954236_

**Comment by drcgjung** [comment]
https://github.com/eclipse-aas4j/aas4j-transformation-library has not been updated since Sep 2023, so it is dead I presume.
We will replace this with another engine or adapt it to

https://github.com/eclipse-aas4j/aas4j/releases/tag/1.0.1 (the version that FAAAST 1.0.1 is using)
