### ISSUE TITLE
Story "Implement interface to AAS registry"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents-aas-bridge#7]
# Story "Implement interface to AAS registry"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to interface an existing AAS registry

## Acceptance Criteria

- registration scripts and schedule
- deregistration scripts and schedule

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/306#issuecomment-1770955937_

**Comment by drcgjung** [comment]
should use a client/wrapper around DTR https://eclipse-tractusx.github.io/docs-kits/kits/Digital%20Twin%20Kit/Adoption%20View%20Digital%20Twin%20Kit

**Comment by drcgjung** [comment]
is an alternative to https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/issues/8

**Comment by drcgjung** [comment]
out of scope
