### ISSUE TITLE
Story "Implement AAS registry"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents-aas-bridge#8]
# Story "Implement AAS registry"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to implement the AAS 3.0 registry interface

## Acceptance Criteria

- additional templates

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/306#issuecomment-1770956815_

**Comment by drcgjung** [comment]
is an alternative to https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge/issues/7

**Comment by drcgjung** [comment]
out of scope
