### ISSUE TITLE
Story "Interface EDC/DGK"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents-aas-bridge#9]
# Story "Interface EDC/DGK"

Repository: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge

## Statement 

As a (potential) KA participant, I want my AAS bridge to interface the EDC and/or the Data Governance Kit.

## Acceptance Criteria

- registration templates and schedule
- deregistration templates and schedule

## Estimation 

5 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/306#issuecomment-1770958517_

**Comment by drcgjung** [comment]
should use a client/wrapper around https://eclipse-tractusx.github.io/docs-kits/kits/Data%20Governance%20Kit/Software%20Development%20View/Data%20Governance%20Kit%20Development%20View and/or https://eclipse-tractusx.github.io/docs-kits/kits/Connector%20Kit/Adoption%20View/connector_kit_adoption_view

**Comment by drcgjung** [comment]
out of scope
